import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { AppProviders } from "@/app/providers";
import { CartProvider } from "@/context/cart";
import { FavoritesProvider } from "@/context/favorites";
import { ToastProvider } from "@/context/toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body
        className={`${inter.variable} antialiased`}
      >
        <AppProviders>
          <CartProvider>
            <FavoritesProvider>
              <ToastProvider>
                <Header />
                <main className="min-h-[calc(100dvh-4rem)]">{children}</main>
              </ToastProvider>
            </FavoritesProvider>
          </CartProvider>
        </AppProviders>
      </body>
    </html>
  );
}
